version: 2
sources:
  - name: tpch 
    database: dev_bootcamp
    schema: tpch
    tables:
      - name: orders_bronze 
        columns:
          - name: O_ORDERKEY
            description: primary key
            tests:
              - unique
              - not_null
      - name: customer_bronze
        columns:
          - name: C_CUSTKEY
            description: primary key
            tests:
              - unique
              - not_null
      - name: lineitem_bronze
        columns:
          - name: L_ORDERKEY
            tests:
              - unique
                  config:
                    severity: warn
              - not_null